### ISSUE TITLE
Svelte won't build when using prerender with mdsvx

### ISSUE THREAD

**Issue by SBV2020** [mattcroat/joy-of-code#155]
Hello @mattcroat,
I have followed your Youtube and blog tutorial on how "Sveltekit Markdown Blog". Everything is working pretty well on local both when prerender option is disabled and enabled.  But once I want to build it with the prerender option enabled (true)  then the issue will be thrown. And if I build the project without prerender option enable (false), then the dynamic route will throw 404 instead. 

I have checked your code in this repo but seem like your code is building it from scratch rather than using mdsvx. 

Here is the log i get when pressing `pnpm build`:
```

vite v4.4.9 building for production...
✓ 44 modules transformed.
.svelte-kit/output/client/_app/version.json                                  0.03 kB │ gzip: 0.05 kB
.svelte-kit/output/client/vite-manifest.json                                 2.47 kB │ gzip: 0.46 kB
.svelte-kit/output/client/_app/immutable/nodes/0.ec4cd187.js                 0.55 kB │ gzip: 0.37 kB
.svelte-kit/output/client/_app/immutable/chunks/preload-helper.a4192956.js   0.89 kB │ gzip: 0.55 kB
.svelte-kit/output/client/_app/immutable/nodes/1.3877a54b.js                 0.98 kB │ gzip: 0.57 kB
.svelte-kit/output/client/_app/immutable/nodes/2.c5c53d50.js                 2.04 kB │ gzip: 1.05 kB
.svelte-kit/output/client/_app/immutable/chunks/singletons.d155d5dc.js       2.85 kB │ gzip: 1.46 kB
.svelte-kit/output/client/_app/immutable/nodes/3.a19eb04d.js                 2.93 kB │ gzip: 1.48 kB
.svelte-kit/output/client/_app/immutable/entry/app.bd70efe8.js               5.01 kB │ gzip: 1.86 kB
.svelte-kit/output/client/_app/immutable/chunks/index.838feb98.js            7.13 kB │ gzip: 2.88 kB
.svelte-kit/output/client/_app/immutable/entry/start.ebf8f3c0.js            24.82 kB │ gzip: 9.78 kB
✓ built in 689ms
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/pc/Desktop/app/.svelte-kit/output/server/entries/pages/blog/1.md' imported from /home/pc/Desktop/app/.svelte-kit/output/server/entries/pages/blog/_slug_/_page.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:326:11)
    at moduleResolve (node:internal/modules/esm/resolve:945:10)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14) {
  code: 'ERR_MODULE_NOT_FOUND'
}
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/pc/Desktop/app/.svelte-kit/output/server/entries/pages/blog/1.md' imported from /home/pc/Desktop/app/.svelte-kit/output/server/entries/pages/blog/_slug_/_page.js
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:326:11)
    at moduleResolve (node:internal/modules/esm/resolve:945:10)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14) {
  code: 'ERR_MODULE_NOT_FOUND'
}

node:internal/event_target:1012
  process.nextTick(() => { throw err; });
                           ^
Error: 500 /blog/1 (linked from /blog)
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file:///home/norin/Desktop/app/node_modules/.pnpm/@sveltejs+kit@1.24.1_svelte@3.59.2_vite@4.4.9/node_modules/@sveltejs/kit/src/core/config/options.js:212:13
    at file:///home/norin/Desktop/app/node_modules/.pnpm/@sveltejs+kit@1.24.1_svelte@3.59.2_vite@4.4.9/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:64:25
    at save (file:///home/norin/Desktop/app/node_modules/.pnpm/@sveltejs+kit@1.24.1_svelte@3.59.2_vite@4.4.9/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:403:4)
    at visit (file:///home/norin/Desktop/app/node_modules/.pnpm/@sveltejs+kit@1.24.1_svelte@3.59.2_vite@4.4.9/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:236:3)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:300:10)
    at [kOnMessage] (node:internal/worker:311:37)
    at MessagePort.<anonymous> (node:internal/worker:212:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v18.16.0
 ELIFECYCLE  Command failed with exit code 1.

``` 

I also commit the code to [this repo](https://github.com/SBV2020/mdsvx-test), just in case you want a quick review. Thanks

**Comment by mattcroat** [comment]
@SBV2020 If you need help make a reproduction and [ask your question on Discord](https://joyofcode.xyz/invite) instead of using issues.
